version: "2"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./data/mongo:/data/db
    networks:
      - private

networks:
  private:
    driver: bridge
