version: "2"

services:
  redis:
    image: redis:5.0.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - private

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./data/mongo:/data/db
    networks:
      - private

networks:
  private:
    driver: bridge
